### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by vejbuch** [galetskyivan/steamcommunity-mobile-confirmations#1]
How to use? :O

**Comment by vejbuch** [comment]
steamcommunityMobileConfirmations.FetchConfirmations received 0 confirmations

But i have 2 confrimations :(

```
var SteamCommunity = require('steamcommunity');
var SteamTotp = require('steam-totp');
var code = SteamTotp.generateAuthCode('MY_SECRET');
console.log(code);
var client = new SteamCommunity();
client.login({
    "accountName": "LOGIN",
    "password": "PASSWORD",
    "twoFactorCode": code
}, function(err, sessionId, cookies, steamguard) {
var SteamcommunityMobileConfirmations = require('steamcommunity-mobile-confirmations');
var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
{
    steamid:         "76561198249721196",
    identity_secret: "MY_SECRET",
    device_id:       this.device_id,
    webCookie:       cookies
});
steamcommunityMobileConfirmations.FetchConfirmations((function (err, confirmations)
{
    if (err)
    {
        console.log(err);
        return;
    }
    console.log('steamcommunityMobileConfirmations.FetchConfirmations received ' + confirmations.length + ' confirmations');
    if ( ! confirmations.length)
    {
        return;
    }
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)
    {
        if (err)
        {
            console.log(err);
            return;
        }
        console.log('steamcommunityMobileConfirmations.AcceptConfirmation result: ' + result);
    }).bind(this));
}).bind(this));

})
```

**Comment by vejbuch** [comment]
where get device id?

**Comment by kaprkns** [comment]
By the logic this should be same device_id, which used in method ITwoFactorService/AddAuthenticator of SteamWebApi when generating shared_secret and identity_secret.

Here we can see example of generating device_identifier: https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/twofactor.js

But in fact here device_id can be any random string taken by this rule:

```
var hash = require('crypto').createHash('sha1');
hash.update(Math.random().toString());
hash = hash.digest('hex');
device_id = 'android:' + hash;
```

**Comment by vejbuch** [comment]
Thanks, i update my script but still say 0 :(

```
var SteamCommunity = require('steamcommunity');
var SteamTotp = require('steam-totp');
var code = SteamTotp.generateAuthCode('=');
console.log(code);
var client = new SteamCommunity();
client.login({
    "accountName": "CSGOCZ3",
    "password": "PW",
    "twoFactorCode": code
}, function(err, sessionId, cookies, steamguard) {
var hash = require('crypto').createHash('sha1');
hash.update(Math.random().toString());
hash = hash.digest('hex');
device_id = 'android:' + hash;
console.log(this.device_id);
var SteamcommunityMobileConfirmations = require('steamcommunity-mobile-confirmations');
var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
{
    steamid:         "76561198249721196",
    identity_secret: "=",
    device_id:       this.device_id,
    webCookie:       cookies,
});

steamcommunityMobileConfirmations.FetchConfirmations((function (err, confirmations)
{
    if (err)
    {
        console.log(err);
        return;
    }
    console.log('steamcommunityMobileConfirmations.FetchConfirmations received ' + confirmations.length + ' confirmations');
    if ( ! confirmations.length)
    {
        return;
    }
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)
    {
        if (err)
        {
            console.log(err);
            return;
        }
        console.log('steamcommunityMobileConfirmations.AcceptConfirmation result: ' + result);
    }).bind(this));
}).bind(this));

})
```

**Comment by vejbuch** [comment]
root@vm16012:~/node_modules# node a.js
C2B58
android:ac48ea7b675d346a1286984c615c8dd644cd9937
steamcommunityMobileConfirmations.FetchConfirmations received 0 confirmations

**Comment by vejbuch** [comment]
steamcommunityMobileConfirmations.FetchConfirmations received 1 confirmations
/root/node_modules/a.js:37
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0]
                                          ^
TypeError: Cannot read property 'AcceptConfirmation' of undefined
    at /root/node_modules/a.js:37:43
    at null.<anonymous> (/root/node_modules/steamcommunity-mobile-confirmations/
index.js:56:3)
    at Request.self.callback (/root/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/root/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:962:12
)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by kaprkns** [comment]
vejbuch, please, remove your shared_secret and identity_secret from your code example.

Remove "this." from line:
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)

I think this misprint.

**Comment by vejbuch** [comment]
THANKS MATE!!!! :)

**Comment by nicoasdd** [comment]
hey sorry but how do u active mobile confirmations? its the same as mail?

**Comment by vejbuch** [comment]
Hi, read this https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/ :)

**Comment by nicoasdd** [comment]
yes i read this from the start :) ty, i dont kno that if u turn on email notif, u get the mobile too :), i manage it to work so TANKS ALL!!!!

**Comment by vejbuch** [comment]
Use this for activate

``` javascript
var username;
var password;
var steamID;
var steamCode;

var fs = require("fs");
var SteamCommunity = require("steamcommunity");
var readline = require("readline");

var community = new SteamCommunity();

var rl = readline.createInterface({
   input: process.stdin,
  output: process.stdout
});

rl.question("Username: ", function(name) {
    username = name;
    rl.question("Password: ", function(pass) {
        password = pass;
        rl.question("Steam ID: ", function(id) {
            steamID = id;
            rl.pause();
            login();
        });
    });
});

function login() {
    community.login({
        "accountName": username,
        "password": password,
    }, function(err, sessionId, cookies, steamguard) {
        if (err) {
            console.log(err);
            rl.resume();
            rl.question("SteamGuard code: ", function(answer) {
                steamCode = answer;
                rl.pause();
                community.login({
                    "accountName": username,
                    "password": password,
                    "authCode": steamCode
                }, function(err, sessionId, cookies, steamguard) {
                    if (err) {
                        console.log(err);
                    } else {
                        enable2fa();
                    };
                });
            });
        } else {
            enable2fa();
        };
    });
};

function enable2fa() {
    community.enableTwoFactor(function(err, resp) {
        if (err) {
            console.log(err)
        } else {
            if (resp.status != 1) {
                console.log("Failed: " + resp.status);
            } else {
                console.log(resp);
                var shared_secret = resp.shared_secret;
                fs.writeFile(username + ".2fa", JSON.stringify(resp), function(err) {
                    if (err) throw err;
                    console.log("Response saved as " + username + ".2fa");
                    rl.resume();
                    rl.question("Activation code: ", function(code) {
                        finalize2fa(shared_secret, code);
                        rl.close();
                    });
                }); 

            };
        };
    });
};

function finalize2fa(shared_secret, code) {
    community.finalizeTwoFactor(shared_secret, code, function(err) {
        if (err) {
            console.log(err);
        } else {
            console.log("2FA finalized successfully");
        };
    });
};
```

**Comment by vejbuch** [comment]
In your mobile set E-mail and use script for activate

**Comment by dencir** [comment]
@vejbuch can i cantact you somehow i have some questions :)

**Comment by bulgakovk** [comment]
@BotBanana I used script above, which provides to enable 2FA. You can write me if you want.

**Comment by dencir** [comment]
@bulgakovk no the enable works fine but i dont get the confirmation of the trades

**Comment by bulgakovk** [comment]
@BotBanana I just started to learn how it works. Need some time.

**Comment by dencir** [comment]
@bulgakovk kk i tried but it doesnt work. add me on steam

**Comment by bulgakovk** [comment]
@vejbuch How did you receive mobile confirmations until 9 Dec?

**Comment by dencir** [comment]
@vejbuch i didnt ? had a working steam bot for a gambling site but without the mobile confirmation thing

**Comment by popularitate** [comment]
vejbuch

I used your code and i get this error:

module.js:338
    throw err;
          ^
Error: Cannot find module 'steamcommunity'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/Bot2/a.js:7:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Can you help ?

Thanks

**Comment by wyvasi** [comment]
you don't have steamcommunity module installed.

**Comment by popularitate** [comment]
I have this:

root@vmi:~# npm install steamcommunity
steamcommunity@3.14.1 node_modules/steamcommunity
├── steam-totp@1.1.0
├── async@1.5.0
├── node-bignumber@1.2.1
├── steamid@0.3.1 (cuint@0.1.5)
├── request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.0, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@5.2.0, tough-cookie@2.2.1, mime-types@2.1.8, bl@1.0.0, http-signature@1.1.0, hawk@3.1.2, har-validator@2.0.3)
├── cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3, lodash@3.10.1)
└── xml2js@0.4.15 (sax@1.1.4, xmlbuilder@4.1.0)

**Comment by Gawrik** [comment]
steamcommunityMobileConfirmations.FetchConfirmations received 0 confirmations
But i have trades for Confirmation
someone can halp me?

**Comment by bulgakovk** [comment]
@Gawrik I can try. Add me: http://steamcommunity.com/profiles/76561198134346437/
