### ISSUE TITLE
steamcommunityMobileConfirmations.AcceptConfirmation result: false

### ISSUE THREAD

**Issue by popularitate** [galetskyivan/steamcommunity-mobile-confirmations#13]
Hello,

After my bot has sent the offer i get this in console:

steamcommunityMobileConfirmations.FetchConfirmations received 1 confirmations
steamcommunityMobileConfirmations.AcceptConfirmation result: false

And the offer is not accepted!

Can you please help me? Thanks

**Comment by doctorwho1914** [comment]
I also have this error.n variable result at line 92 returns this message:
" It looks like there is a problem with the time or timezone settings on your device. You will not be able to act on any confirmations until that problem is resolved "

**Comment by popularitate** [comment]
So, on my Linux server i have this:

root@:~# date
Fri Jan  1 23:00:08 CET 2016

What can i do to fix this ?

**Comment by doctorwho1914** [comment]
I set GMT-7 and it worked

**Comment by popularitate** [comment]
Worked for me as well, i just set the server default time.

Thanks so much for your help !

**Comment by lasilix** [comment]
GMT -7 not work for me :(
