### ISSUE TITLE
Cannot accept more confirmations per one fetch

### ISSUE THREAD

**Issue by gamelaster** [galetskyivan/steamcommunity-mobile-confirmations#2]
After a little using of this library, i have problem, when has been a Two confirmations, its accepts only first. That is okay, becouse on sample its accepting only a first confirmation.
So i writed for each accept confirmation. But this not work, still, first accepted without error and with response true, and second not accepted, without error and with response false.

To solve this, just after accepting first, check if length of confirmations is bigger than one, just again execute a function to fetch confirmation and accept it!

**Comment by scholtzm** [comment]
You can only accept 1 confirmation per 1 second. Your code probably fires both acceptations with the same timestamp and thus the same key.

**Comment by gamelaster** [comment]
@scholtzm Hmm, that is maybe right, and for me its "again fetch" working becouse fetching new confirmations take a some time! :-)

**Comment by scholtzm** [comment]
Fetching confirmations again and again is unnecessary and might yield worse results in the end.
