### ISSUE TITLE
What is WebCookie?

### ISSUE THREAD

**Issue by heinhtetaung-node** [galetskyivan/steamcommunity-mobile-confirmations#22]
> var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
> {
>   steamid:         "....",
>     identity_secret: "...=",
>     device_id:       "android:...",
>     webCookie:       webCookie
> });

In webCookie I don't know what should I fill. Please help me.

**Comment by Yashko** [comment]
you get it after [webLogOn](https://github.com/Alex7Kom/node-steam-weblogon)

```
steamWebLogOn.webLogOn(function(sessionID, **newCookie**) {
```
