### ISSUE TITLE
Cannot read property 'AcceptConfirmation' of undefined

### ISSUE THREAD

**Issue by Freaders** [galetskyivan/steamcommunity-mobile-confirmations#4]
Im geting this error. Does anybody know what could be wrong?

```
[18:5:19:102] Message: "webLogOn ok"
steamcommunityMobileConfirmations.FetchConfirmations received 2 confirmations
/bot2/steambot.js:828
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0]
                                          ^
TypeError: Cannot read property 'AcceptConfirmation' of undefined
    at /bot2/steambot.js:828:43
    at null.<anonymous> (/bot2/node_modules/steamcommunity-mobile-confirmations/index.js:56:3)
    at Request.self.callback (/bot2/node_modules/steamcommunity-mobile-confirmations/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/bot2/node_modules/steamcommunity-mobile-confirmations/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/bot2/node_modules/steamcommunity-mobile-confirmations/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```

``` javascript
function reWebLogOn(steam, callback) {
    steam.webLogOn(function(newCookie){
        helper.msg('webLogOn ok');
        cookies = newCookie;
        offers.setup({
            sessionID: currentSessionId,
            webCookie: newCookie
        }, function(){
            if (typeof callback == "function") {
                callback();
            }
        });
        var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
    {
      steamid:         config.steamid,
      identity_secret: config.identitySecret,
      device_id:       config.deviceId,
      webCookie:       newCookie,
    });

    steamcommunityMobileConfirmations.FetchConfirmations((function (err, confirmations)
{
    if (err)
    {
        console.log(err);
        return;
    }
    console.log('steamcommunityMobileConfirmations.FetchConfirmations received ' + confirmations.length + ' confirmations');
    if ( ! confirmations.length)
    {
        return;
    }
    this.steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)
    {
        if (err)
        {
            console.log(err);
            return;
        }
        console.log('steamcommunityMobileConfirmations.AcceptConfirmation result: ' + result);
    }).bind(this));
}).bind(this));

    });  
}
```

**Comment by Freaders** [comment]
fixed, just remove "this." from "this.steamcommunityMobileConfirmations.AcceptConfirmation"

**Comment by meitinglei** [comment]
I use the same code, but i received 0 confirmations,in fact there are 2confirmations in the bot...

**Comment by meitinglei** [comment]
steamClient.on('logOnResponse', function (logonResp) {
        if (logonResp.eresult === Steam.EResult.OK) {
            log("Logged on");
            steamWebLogOn.webLogOn(function (sessionID, newCookie) {
                getSteamAPIKey({
                    sessionID: sessionID,
                    webCookie: newCookie
                }, function (err, APIKey) {
                    if (err) {
                        debug('Error while getSteamAPIKey: "' + err + '"');
                        steamClient.disconnect();
                        steamClient.connect();
                        return
                    }
                    offers.setup({
                        sessionID: sessionID,
                        webCookie: newCookie,
                        APIKey: APIKey
                    }, function (err) {
                        if (err) {
                            return
                        }
                    })
                });
                var steamcommunityMobileConfirmations = new SteamcommunityMobileConfirmations(
                    {
                        steamid:         "76561198140921899",
                        identity_secret: "=",
                        device_id:       "android:7cdafa0efa0c4c7b3f805c8741a589f060be48ea",
                        webCookie:       newCookie
                    });

                steamcommunityMobileConfirmations.FetchConfirmations((function (err, confirmations)
                {
                    if (err)
                    {
                        console.log(err);
                        return;
                    }
                    console.log('steamcommunityMobileConfirmations.FetchConfirmations received ' + confirmations.length + ' confirmations');
                    if ( ! confirmations.length)
                    {
                        return;
                    }
                    steamcommunityMobileConfirmations.AcceptConfirmation(confirmations[0], (function (err, result)
                    {
                        if (err)
                        {
                            console.log(err);
                            return;
                        }
                        console.log('steamcommunityMobileConfirmations.AcceptConfirmation result: ' + result);
                    }).bind(this));
                }).bind(this));
            });
        } else {
        }
    });

**Comment by Nikoly0072** [comment]
Спасибо
